version: "2"
services:
  
  restaurant:
    image: paidy-restaurant
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
        - 3333:3333

    environment: 
      - DATABASE_URL=postgres://postgres:password@pgdb/test
      - HOST=0.0.0.0
      - PORT=3333
      - MAX_TABLES=100

    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgdb:
    container_name: pgdb
    image: postgres:latest
    ports: ["5432:5432"]
    environment: 
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Tokyo
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

